---

- hosts: all
  become: yes
  become_method: sudo
  roles:
    - common
  tasks:
  - name: Copy Index Page Files
    copy: src=templates/apps dest=/opt/SP/apps/tomcat/webapps/ROOT mode=0644
    notify: 
    - Restart Tomcat


  - name: Copy Petclinic Project War Files
    copy: src=templates/*.war dest=/opt/SP/apps/tomcat/webapps/ROOT.war mode=0644

  handlers:
  - name: Restart Tomcat
    shell: "nohup sh /opt/SP/apps/tomcat/bin/catalina.sh start" 
